### ISSUE TITLE
Oversized-images demo not working anymore

### ISSUE THREAD

**Issue by gmetais** [GoogleChromeLabs/feature-policy-demos#24]
Hi there!

Two months ago, I was able to get this demo working on my Chrome browser. It is not the case anymore.

Chrome version: 83.0
Experimental Web Platform features: enable
Experimental Productivity Features: enable (as explained [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/oversized-images))
Browser restarted after flags change.
I've also tried adding a Feature-Policy header with the [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj) extension.

Nothing happens, all images are visible in the demo. Was this Feature-Policy removed from Chrome?

**Comment by huchenlei** [comment]
The image policies are moved from feature policy to [document policy](https://github.com/w3c/webappsec-permissions-policy/blob/master/document-policy-explainer.md).

We are currently working on refreshing the demos. Sorry about the broken demos right now.

**Comment by gmetais** [comment]
Thanks a lot @huchenlei. I'm closing the issue :)
