### ISSUE TITLE
Demos should reflect name change from 'Feature Policy' to 'Permissions Policy'

### ISSUE THREAD

**Issue by jpmedley** [GoogleChromeLabs/feature-policy-demos#32]
https://www.chromestatus.com/features/5745992911552512
https://w3c.github.io/webappsec-permissions-policy/

**Comment by jpchase** [comment]
The source for demos have already been updated to reflect the rename/split to Permissions Policy and Document Policy (e.g. #30, #31). We do need to deploy the changes to the running site - lost track of that.

**Comment by jpchase** [comment]
We've finally deployed the changes, so the current version of the site reflects the appropriate naming. Feel free to reopen if you notice any references to the old naming.

**Comment by jpmedley** [comment]
Thanks!
